# Generated by Django 5.1.3 on 2024-11-26 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignment_allow_late_submission_classroom_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(help_text='Duration of the exam (e.g., 2:30:00 for 2 hours and 30 minutes)'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
